participants:
  - el_type: geth
    cl_type: prysm
    cl_image: "gcr.io/offchainlabs/prysm/beacon-chain:local"
    cl_extra_params:
    - --activate-zkvm
    - --zkvm-generation-proof-types=0,1
    vc_image: "ethpandaops/prysm-validator:develop"
    count: 2
additional_services:
  - dora
