load("@prysm//tools/go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "dummy.go",
        "runner.go",
        "type.go",
        "util.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v6/ssz-query/testutil",
    visibility = ["//visibility:public"],
    deps = [
        "//ssz-query:go_default_library",
        "//testing/assert:go_default_library",
        "//testing/require:go_default_library",
        "@com_github_ethereum_go_ethereum//common/hexutil:go_default_library",
        "@com_github_ferranbt_fastssz//:go_default_library",
    ],
)
