# This package has been fully deprecated. All code moved to
# //beacon-chain/rpc/core/blockproduction
# Delete this directory entirely.

load("@prysm//tools/go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "log.go",
        "proposer.go",
        "server.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/beacon-chain/rpc/prysm/v1alpha1/validator",
    visibility = ["//beacon-chain:__subpackages__"],
)
