# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: changelog

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  run-changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download unclog binary
        uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # 1.1.2
        with:
          repo: OffchainLabs/unclog
          version: "tags/v0.1.3"
          file: "unclog"

      - name: Get new changelog files
        id: new-changelog-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            changelog/**.md

      - name: Run lint command
        env:
          ALL_ADDED_MARKDOWN: ${{ steps.new-changelog-files.outputs.added_files }}
        run: chmod +x unclog && ./unclog check -fragment-env=ALL_ADDED_MARKDOWN
